
export function itemRollFlow() {
    const friendlyTarget = this.applyDefaultTargetsAsEffective(
        this.sequence(
            this.performSaveDamageRoll(
                this.applyDamage()
            ),
            this.applyEffects()
        )
    )

    const nonAttack = this.pick(
        this.isSave(
            this.performSavingThrow(
                this.hasDamage(
                    this.performSaveDamageRoll(
                        this.sequence(
                            this.applyDamage(),
                            this.applyEffects()
                        )
                    )
                ),
                this.applyEffects()
            )
        ),
        this.otherwise(
            friendlyTarget
        )
    )
    
    return this.sequence(
        this.hasDuration(
            this.hasConcentration(
                this.applyConcentration()
            ),
            this.hasAreaTarget(
                this.applyDurationEffect()
            )
        ),
        this.pick(
            this.isTokenTargetable(
                this.sequence(
                    this.applySelectedTargets(),
                    this.pick(
                        this.isAttack(
                            this.performAttackRoll(
                                this.sequence(
                                    this.hasDamage(
                                        this.performAttackDamageRoll(
                                            this.applyDamage(
                                                this.triggerAttackConditions()
                                            )
                                        )
                                    ),
                                    this.applyEffects(
                                        this.triggerAttackConditions()
                                    )
                                )
                            )
                        ),
                        this.otherwise(
                            nonAttack
                        )
                    )
                )
            ),
            this.hasAreaTarget(
                this.hasDamageOrEffects(
                    this.confirmTargets(
                        nonAttack
                    )
                )
            ),
            this.isSelfTarget(
                friendlyTarget
            )
        )
    )
}
